### ISSUE TITLE
BOM Incomplete & Design files request

### ISSUE THREAD

**Issue by schmarrele** [petl/USB-C-cable-tester-C2C-caberQU#3]
Hi, 

I would like to order the board on my own, but the BOM seems to be incomplete.
Can you please update which specific MPN you use? (especially for the USB-C plugs and CR2032 holder)

Will you publish the (Eagle?) design files too?
Thanks

**Comment by snadorp** [comment]
Very much interested in the Eagle files as well.

**Comment by petl** [comment]
That's not really planned, the files are as a guide and not to make a commercial clone of this, sorry.

**Comment by florisvde** [comment]
For anyone still looking for this: a good samaritan made a [fully open source version](https://github.com/CountParadox/USB-C-cable-tester-C2C-open) of this project, with a [fully specified BOM](https://github.com/CountParadox/USB-C-cable-tester-C2C-open/blob/main/BOM/Kickstarter%20Edition/2022_USB_C_cable_tester_BOM_LCSC_v1.csv). Not sure if that BOM is compatible with the v2 gerbers posted here by @petl, so I'd suggest having @CountParadox's boards made instead.

In @petl's [manual](https://github.com/petl/USB-C-cable-tester-C2C-caberQU/blob/main/documentation/v2/caberQU_manual_v2.3.pdf) the most important MPNs can also be found:

| Reference Designator | QTY | MPN |
| -------- | ------- | ------- |
| J3-4  | 2 | [GCT USB4080-03-A](https://www.digikey.nl/en/products/detail/gct/USB4080-03-A/14659819) |
| G1 | 1 | [MYOUNG MY-2032-12](https://www.lcsc.com/product-detail/C964833.html) |

Since I'm ordering parts from DigiKey, I'm going to try the following parts for @petl's v2 PCB:
| Reference Designator | QTY | MPN |
| -------- | ------- |------- |
| J3-J4  | 2 | [GCT USB4080-03-A](https://www.digikey.nl/en/products/detail/gct/USB4080-03-A/14659819) |
| G1 | 1 | [Keystone 3034](https://www.digikey.nl/en/products/detail/keystone-electronics/3034/4499289) |
| LED1-LED25 | 25 | [Lite-On Inc. LTST-C171KSKT](https://www.digikey.nl/en/products/detail/liteon/LTST-C171KSKT/386803) |
| R1-R25 | 25 | [YAGEO RT0805DRE07100RL](https://www.digikey.nl/en/products/detail/yageo/RT0805DRE07100RL/1078369) |
| C1 | 1 | [YAGEO CC0805KKX7R7BB105](https://www.digikey.nl/en/products/detail/yageo/CC0805KKX7R7BB105/2103103) |

**Comment by CountParadox** [comment]
@florisvde there's other open source projects now that do more than just USB C :) 

See
https://github.com/alvarop/usb_c_cable_tester
